parser: babel-eslint
env:
  browser: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-vars:
    - error
  react/prop-types:
    - 0
  react/display-name:
    - 0
  no-console:
    - warn
  no-unused-vars:
    - warn
  # indent:
  #   - error
  #   - 4
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - error
  #   - single
  semi:
    - warn
    - never
